[project]
name = "nasa-landsat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.2.0",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
]
